#!/usr/bin/env bash
# a Bash script that installs nginx on our web-01 server
# /redirect_me is redirecting to another page
#apt-get -y update
#apt-get -y install nginx
#ufw allow 'Nginx HTTP'
myc="\n\trewrite \^\/redirect_me\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
st="server {"
sed -i "0,/$st/{s/$st/$st$myc/}" /etc/nginx/sites-available/default
#service nginx start
