#!/usr/bin/env bash
# commands to debug the container
st="\tlisten 8080 default_server\;"
newst="\tlisten 80 default_server\;"
st2="\tlisten \[::\]:8080 default_server"
newst2="\tlisten \[::\]:80 default_server"
sudo sed -i "0,/$st/{s/$st/$newst/}" test
sudo sed -i "0,/$st2/{s/$st2/$newst2/}" test
